### PR TITLE
Check that address is set during Register

### LINKED ISSUE #30: Does not actually include the host when sending a port-only registration
Somewhere in the flynn docs it says registering with a port only would make discoverd send it out with it's own ip, but this is not currently the case. 

I wasn't entirely sure how this would be implemented (post-process the event from etcd?), so I wanted to raise it first for now.

### PR DESCRIPTION
**Pull request by titanous**
Closes #30.

### CODE REVIEW

**Comment by titanous** [comment]
ping @progrium

**Comment by progrium** [comment]
What would make more sense to me is that if some configuration is required like this then it should fail before it starts as opposed to run and fail at runtime.

**Comment by titanous** [comment]
Yeah, but it's not exactly _required_. If consumers always set the host part of the address, then `EXTERNAL_IP` is never used.

That being said, if you think it's better to fail on boot if `EXTERNAL_IP` is not set, we can do that. It just means that running `discoverd` with no env/args will result in failure.

**Comment by progrium** [comment]
Okay, no I guess this works. Wouldn't want to preclude a service from
specifying its own IP.

On Sun, Feb 9, 2014 at 7:03 PM, Jonathan Rudenberg <notifications@github.com

> wrote:
> 
> Yeah, but it's not exactly _required_. If consumers always set the host
> part of the address, then EXTERNAL_IP is never used.
> 
> That being said, if you think it's better to fail on boot if EXTERNAL_IPis not set, we can do that. It just means that running
> discoverd with no env/args will result in failure.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/discoverd/pull/31#issuecomment-34593888
> .

## 

Jeff Lindsay
http://progrium.com

**Pull request merged**
